### ISSUE TITLE
Signing dynamic zones with zkt?

### ISSUE THREAD

**Issue by eNBeWe** [hzuleger/ZKT#5]
I just started a small test setup with dnssec and wanted to use ZKT for automatic dnssec management.
The zones I am using are dynamic zones. I found the parameter -d in zkt-signer but that seems to be broken. Is the feature not ready? How should I use zkt with dynamic zones?

**Comment by hzuleger** [comment]
Hi,

> I just started a small test setup with dnssec and wanted to use ZKT for
> automatic dnssec management.
ZKT is able to sign and manage dynamic zones, but from my point of view
it is not the best tool for this.
With option -d zkt-signer will freeze the zone, than resign the zone
file and thaw it again.
So, whenever you (re)sign a dynamic zone, there is a small service outage.
On the other side, BIND itself has the ability to sign dynamic zones by
itself, so I would recommend to use this for dynamic zones (ZKT was
build at a time BIND wasn't able to resign dynamic zones).

> The zones I am using are dynamic zones. I found the parameter -d in
> zkt-signer but that seems to be broken. Is the feature not ready? How
> should I use zkt with dynamic zones?
It is not very well documented because of the restrictions above-mentioned.
However, option -d pick up only those zone files named ".dsigned".
So I guess you have to rename your (signed) dynamic zone file to
"zone.dsigned".

See also the example in examples/flat/dyn.example.net:

ZKT/examples/flat$ ./zkt-signer -v -d
parsing zone "dyn.example.net." in dir "./dyn.example.net"
	Check RFC5011 status
	Check KSK status
	No active KSK found: generate new one
	Check ZSK status
	No active ZSK found: generate new one
	Re-signing necessary: Modified zone key set
	Writing key file "./dyn.example.net/dnskey.db"
	Signing zone "dyn.example.net."
	freeze dynamic zone "dyn.example.net."
	Dynamic Zone signing: copy old signed zone file
./dyn.example.net/zone.db.dsigned to new input file
./dyn.example.net/zone.db
	thaw dynamic zone "dyn.example.net."
	Signing completed after 0s.

HTH
 Holger

**Comment by eNBeWe** [comment]
Hi,

okay, the .dsigned part is probably the issue on my end.

I agree that dynamic signing in bind is preferable to zkt. Primarily I was interested in using zkt for automatic key rollover management (as there is no function for that in bind).

**Comment by jschlyter** [comment]
You might also want to take a look at https://github.com/opendnssec/ods4bind that interfaces OpenDNSSEC with the BIND online signer.
